---
title: "Lab 03 - Nobel laureates"
author: "wang jiawu, Millie, Ruhani, Olivia, Paula"
date: "`r Sys.Date()`"
output: html_document
---


### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse) 
```

```{r chunk1, message = FALSE}
nobel <- read_csv("data/nobel.csv")
```

### Exercise 1

#### Narrative

935 observations. 26 variables. Each row represents Nobel prize laureates.


### Exercise 2

#### Code

```{r nobel-living}

nobel_living <- 
  nobel %>% 
  filter( !is.na(country), 
         gender != "org", 
         is.na(died_date))
```

#### Narrative



### Exercise 3

#### Code

```{r facet-bar-plot}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(country == "USA", "USA", "Other")
  )
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))
nobel_living_science %>% 
  ggplot() +
  geom_bar(mapping = aes(x=country_us)) +
  facet_wrap(~category) +
  coord_flip()
```
#### Narrative

*Remove this text and add your answer here.*


### Exercise 4

#### Code

```{r born-country-us}
  nobel%>%
  mutate(born_country_us = 
           if_else(born_country == "USA", "USA", "Other")) %>%
  filter(born_country_us == "USA")
```

271 x 27

### Exercise 5

#### Narrative

*Remove this text and add your answer here.*

#### Code

```{r facet-bar-plot-redo}
nobel_living <- nobel_living %>%
  mutate(country_us = if_else(country == "USA", "USA", "Other"), born_country_us = if_else(born_country == "USA", "USA", "Other"))
    
nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

nobel_living_science %>% 
  ggplot() +
  geom_bar(mapping = aes(x=country_us, fill=born_country_us)) +
  facet_wrap(~category) +
  coord_flip()
  
```


### Exercise 6

#### Code

```{r born-country}
nobel %>%
  filter(country == "USA", born_country != "USA") %>%
  ggplot() +
  geom_bar(mapping= aes(x = fct_infreq(born_country))) +
             coord_flip()

```

#### Narrative

*Remove this text and add your answer here.*